name: 'fail composite test'
description: 'Test Failures in composite actions'

inputs:
  success:
    description: '"true" if workflow is successful'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@main
      env:
        SUCCESS: ${{ inputs.success }}
      with: 
        script: |
          console.log("Success?")
          console.log(process.env.SUCCESS)
