name: 'fail composite test'
description: 'Test Failures in composite actions'

runs:
  using: "composite"
  steps:
    - run: true
      name: step1
      shell: bash

    - run: false
      name: step2
      shell: bash

    - run: true
      name: step3
      shell: bash

    - run: echo "ALWAYS (succeeded? ${{ success() }})"
      name: always
      if: always()
      shell: bash

    - run: echo "FAILURE"
      name: fail
      if: failure()
      shell: bash

