name: 'fail composite test'
description: 'Test Failures in composite actions'

inputs:
  status:    
    description: 'status of the workflow'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@main
      with: 
        script: |
          console.log(${{ inputs.status }})
          console.log(${{ jobs }})
          console.log(context)
