name: 'fail composite test'
description: 'Test Failures in composite actions'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - run: true
      id: step1
      shell: bash

    - run: false
      id: step2
      shell: bash

    - run: true
      id: step3
      shell: bash

    - run: echo "FAILURE"
      id: fail
      if: failure()
      shell: bash
