name: 'fail composite test'
description: 'Test Failures in composite actions'

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@main
      with: 
        script: |
          console.log(github)
          console.log(context)
