name: 'fail composite test'
description: 'Test Failures in composite actions'

runs:
  using: "composite"
  steps:
    - run: true
      id: step1
      shell: bash

    - run: true
      id: step2
      shell: bash

    - run: true
      id: step3
      shell: bash

    - run: echo "ALWAYS"
      id: always
      if: always()
      shell: bash

    - run: echo "FAILURE"
      id: fail
      if: failure()
      shell: bash

