name: 'fail composite test'
description: 'Test Failures in composite actions'

inputs:
  status:    
    description: 'status of the workflow'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@main
      env:
        STATUS: ${{ inputs.status }}
      with: 
        script: |
          console.log("status:")
          console.log(process.env.STATUS)
