name: "workflow to test context.workflow"

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VARIABLE: "foo"
    steps:
      - run: |
          echo "$VARIABLE"
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            console.log("context test")
            console.log(context)
            console.log(`context.workflow ${context.workflow}`)
            
            const run = await github.rest.actions.getWorkflowRun( {
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
            })
            console.log(run)
