name: Test create-issue and close-issue

on:
  workflow_dispatch

jobs:
  create:
    runs-on: ubuntu-latest
    permissions:
      issues: 'write'
    steps:
      - name: Create issue
        uses: jku/create-issue/.github/actions/open-workflow-issue@main
        with:
          token: ${{ github.token }}

  close:
    runs-on: ubuntu-latest
    needs: [create]
    permissions:
      issues: 'write'
    steps:
      - name: Close issue
        uses: jku/create-issue/.github/actions/close-workflow-issue@main
        with:
          token: ${{ github.token }}
