name: Test create-issue and close-issue

on:
  workflow_dispatch

jobs:
  create:
    runs-on: ubuntu-latest
    permissions:
      issues: 'write'
      actions: 'read'
    steps:
      - name: Create issue
        uses: sigstore/sigstore-probers/.github/actions/open-workflow-issue@main

  close:
    runs-on: ubuntu-latest
    needs: [create]
    permissions:
      issues: 'write'
      actions: 'read'
    steps:
      - name: Close issue
        uses: sigstore/sigstore-probers/.github/actions/close-workflow-issue@main
