name: Test composite failures

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          true

  test:
    runs-on: ubuntu-latest
    needs: [job1]
    if: always() && !cancelled()
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./.github/actions/composite-test
        with:
          status: ${{ failure() }}
