name: Test composite failures

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref:
            'another-branch'
      - run: |
          false

  test:
    runs-on: ubuntu-latest
    needs: [job1]
    if: always() && !cancelled()
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./.github/actions/composite-test
        with:
          success: ${{ !contains(needs.*.result, 'failure') }}
