name: "workflow to test pages artifact"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          date > ./content
      - uses: actions/upload-pages-artifact@v2
        with:
          path: "./"

  # Deploy job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
        
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with: 
          name: "github-pages"
      - run: |
          PUBDIR=$(mktemp -d --tmpdir=./)
          unzip -p github-pages.zip | tar --extract --directory=$PUBDIR
          ls $PUBDIR
