name: Test create-issue and close-issue

on:
  workflow_dispatch

jobs:
  succeeding-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          true

  succeeding-job2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          false  # test failing?

  failing-job:
    runs-on: ubuntu-latest
    needs: [succeeding-job2]
    steps:
      - run: |
          true # test succeding?

  create:
    runs-on: ubuntu-latest
    needs: [failing-job, succeeding-job, succeeding-job2]
    if: failure()
    permissions:
      issues: 'write'
      actions: 'read'
    env:
      NEEDS:  ${{ toJSON(needs.*.result) }}
    steps:
      - run: echo "NEEDS $NEEDS"
      - name: Create issue on failure
        uses: sigstore/sigstore-probers/.github/actions/open-workflow-issue@main
        with:
          comment_for_each_failure: true

  create-another:
    runs-on: ubuntu-latest
    needs: [create]
    if: failure()
    permissions:
      issues: 'write'
      actions: 'read'
    steps:
      - name: Create issue on failure
        uses: sigstore/sigstore-probers/.github/actions/open-workflow-issue@main
        with:
          comment_for_each_failure: true

  close:
    runs-on: ubuntu-latest
    needs: [create-another]
    if: failure()
    permissions:
      issues: 'write'
      actions: 'read'
    steps:
      - name: Close issue
        uses: sigstore/sigstore-probers/.github/actions/close-workflow-issue@main
